export type Product = {
  id: string;
  name: string;
  category: string;
  description: string;
  price: number;
  image_url: string;
  badge: string;
  active: boolean;
};

function publicImage(path: string) {
  return `/${path.split("/").map(encodeURIComponent).join("/")}`;
}

function product(
  id: string,
  name: string,
  category: string,
  description: string,
  price: number,
  imagePath: string,
  badge: string,
): Product {
  return {
    id,
    name,
    category,
    description,
    price,
    image_url: publicImage(imagePath),
    badge,
    active: true,
  };
}

export const fallbackCatalog: Product[] = [
  product(
    "cloud-plush-blanket",
    "Cloud Plush Blanket",
    "Plush blankets",
    "A softer kind of slow morning",
    28500,
    "plush_blanket/Cozy Sherpa Throw - Ultimate Knit Blanket_ Cozy Comfort.jpg",
    "Bestseller",
  ),
  product(
    "weekend-fleece-throw",
    "Weekend Fleece Throw",
    "Plush blankets",
    "Made for the long way home",
    22500,
    "plush_blanket/Bedsure Throw Blankets.jpg",
    "Soft touch",
  ),
  product(
    "rose-garden-blanket",
    "Rose Garden Blanket",
    "Plush blankets",
    "A little warmth in a lovely shade",
    32500,
    "plush_blanket/Plush Throw Blankets on a Budget _ Dusty Rose, White & Gray Stack.jpg",
    "Customer favorite",
  ),
  product(
    "sage-cloud-blanket",
    "Sage Cloud Blanket",
    "Plush blankets",
    "Easy comfort, all year round",
    38500,
    "plush_blanket/Faux Fur Throw Blanket Cozy Warm Plush Blanket for Sofa or Bed.jpg",
    "Just landed",
  ),
  product(
    "everyday-tote",
    "Everyday Tote Bag",
    "Tote bags",
    "Room for all your little things",
    18500,
    "tote_bag/Light Tote Bag.jpg",
    "Everyday favorite",
  ),
  product(
    "market-day-canvas",
    "Market Day Canvas Tote",
    "Tote bags",
    "A roomy carry-all for daily plans",
    12500,
    "tote_bag/tote bag  design.jpg",
    "Easy carry",
  ),
  product(
    "woven-weekend-tote",
    "Woven Weekend Tote",
    "Tote bags",
    "A relaxed shape with room to spare",
    24500,
    "tote_bag/download (2).jpg",
    "Weekend edit",
  ),
  product(
    "little-day-tote",
    "Little Day Tote",
    "Tote bags",
    "Your light and lovely plus-one",
    16500,
    "tote_bag/download (3).jpg",
    "New color",
  ),
  product(
    "studio-gym-mat",
    "Studio Gym Mat",
    "Gym mats",
    "A little space to reset",
    32000,
    "Gym-Mat/Premium Ribbed Yoga Mat with Carrying Straps for Home Workouts.jpg",
    "New arrival",
  ),
  product(
    "daily-flow-mat",
    "Daily Flow Mat",
    "Gym mats",
    "Comfort for every stretch",
    28500,
    "Gym-Mat/My 10 Best Meditation Mats for Not Hurting Your Knees.jpg",
    "Studio pick",
  ),
  product(
    "cork-balance-mat",
    "Cork Balance Mat",
    "Gym mats",
    "A grounded start to your practice",
    42000,
    "Gym-Mat/Bodenmatten, 6 Stück, Gummi-Oberfläche & EVA-Schaum, 315 x 315 mm, Trainingsmatten mit 24 Quadratfuß.jpg",
    "Natural touch",
  ),
  product(
    "fold-and-go-mat",
    "Fold & Go Travel Mat",
    "Gym mats",
    "Your practice goes where you go",
    35500,
    "Gym-Mat/How weather changes can affect joint comfort.jpg",
    "Travel ready",
  ),
  product(
    "daily-essentials-set",
    "Daily Essentials Set",
    "Personal essentials",
    "The details that make a day",
    14500,
    "Personal-Essentials/Groomsmen Gifts Personalized Leather Toiletry Bag _ Custom Dopp Kit _ Shaving Kit _ Gift for Him.jpg",
    "A thoughtful pick",
  ),
  product(
    "glow-ritual-kit",
    "Glow Ritual Kit",
    "Personal essentials",
    "A few gentle minutes for you",
    22500,
    "Personal-Essentials/gorchis New Fashion Clutch Bag With Password Lock And Multiple Pockets, Handheld Bag For Phone And Accessories, Suitable For Business And Casual Occasions For Travel Fall Stuff Anti-Theft Portable….jpg",
    "Feel-good ritual",
  ),
  product(
    "fresh-start-care-set",
    "Fresh Start Care Set",
    "Personal essentials",
    "Everyday care, gathered together",
    18500,
    "Personal-Essentials/FASTRACK unisex black Analog watch.jpg",
    "Giftable",
  ),
  product(
    "little-travel-essentials",
    "Little Travel Essentials",
    "Personal essentials",
    "Your daily favorites, ready to go",
    9500,
    "Personal-Essentials/Термобутылка чёрная.jpg",
    "On-the-go",
  ),
  product(
    "active-day-duffel",
    "Active Day Duffel",
    "Gym bags",
    "Room for your kit and your plans",
    28500,
    "Dolphin-bags/Adidas Crossbody Bag JZ0608 _ Unisex One Shoulder Sports Tote Bag Outdoor Casual Fitness Travel Bag.jpg",
    "Best seller",
  ),
  product(
    "move-light-backpack",
    "Move Light Backpack",
    "Gym bags",
    "Hands-free, ready for anything",
    32500,
    "Dolphin-bags/adidas Unisex Bolsa de Deporte Essentials.jpg",
    "New arrival",
  ),
  product(
    "after-class-weekender",
    "After Class Weekender",
    "Gym bags",
    "From studio session to the weekend",
    38500,
    "Dolphin-bags/Ultimate Gym Bag Aesthetic _ Aesthetic Workout Essentials.jpg",
    "Roomy favorite",
  ),
  product(
    "quick-reset-sling",
    "Quick Reset Sling",
    "Gym bags",
    "Just the essentials, carried easy",
    19500,
    "Dolphin-bags/40 Of The Best Gym Bags For Carrying _All_ Your___.jpg",
    "Light carry",
  ),
  product(
    "dolphin-weekender",
    "Dolphin Weekender Bag",
    "Dolphin bags",
    "Ready when you are",
    26000,
    "Dolphin-bags/Personalised Gym Bag for the Motivated Fitness….jpg",
    "Just landed",
  ),
  product(
    "dolphin-city-tote",
    "Dolphin City Tote",
    "Dolphin bags",
    "A polished carry-all for every day",
    22500,
    "Dolphin-bags/TRAVEL BAG.jpg",
    "City favorite",
  ),
  product(
    "dolphin-travel-carryall",
    "Dolphin Travel Carryall",
    "Dolphin bags",
    "A little more room for the journey",
    36500,
    "Dolphin-bags/633952085093384586.jpg",
    "Travel edit",
  ),
  product(
    "dolphin-mini-crossbody",
    "Dolphin Mini Crossbody",
    "Dolphin bags",
    "Small bag, lovely company",
    18500,
    "Dolphin-bags/37 Types of Bags For Women.jpg",
    "Easy favorite",
  ),
];
